__version__ = "0.13.3.dev0"


# from .auto import (
#     AutoPeftModel,
#     AutoPeftModelForCausalLM,
#     AutoPeftModelForSequenceClassification,
#     AutoPeftModelForSeq2SeqLM,
#     AutoPeftModelForTokenClassification,
#     AutoPeftModelForQuestionAnswering,
#     AutoPeftModelForFeatureExtraction,
# )
from .mapping import (
    MODEL_TYPE_TO_PEFT_MODEL_MAPPING,
    PEFT_TYPE_TO_CONFIG_MAPPING,
    get_peft_config,
    get_peft_model,
    inject_adapter_in_model,
)
# from .mixed_model import PeftMixedModel
# from .peft_model import (
#     PeftModel,
#     PeftModelForCausalLM,
#     PeftModelForSeq2SeqLM,
#     PeftModelForSequenceClassification,
#     PeftModelForTokenClassification,
#     PeftModelForQuestionAnswering,
#     PeftModelForFeatureExtraction,
#     get_layer_status,
#     get_model_status,
# )
# from .tuners import (
#     AdaptionPromptConfig,
#     AdaptionPromptModel,
#     LoraConfig,
#     LoraRuntimeConfig,
#     LoftQConfig,
#     EvaConfig,
#     LoraModel,
#     LoHaConfig,
#     LoHaModel,
#     LoKrConfig,
#     LoKrModel,
#     IA3Config,
#     IA3Model,
#     AdaLoraConfig,
#     AdaLoraModel,
#     BOFTConfig,
#     BOFTModel,
#     PrefixEncoder,
#     PrefixTuningConfig,
#     PromptEmbedding,
#     PromptEncoder,
#     PromptEncoderConfig,
#     PromptEncoderReparameterizationType,
#     PromptTuningConfig,
#     PromptTuningInit,
#     MultitaskPromptTuningConfig,
#     MultitaskPromptTuningInit,
#     OFTConfig,
#     OFTModel,
#     PolyConfig,
#     PolyModel,
#     LNTuningConfig,
#     LNTuningModel,
#     VBLoRAConfig,
#     VBLoRAModel,
#     VeraConfig,
#     VeraModel,
#     FourierFTConfig,
#     FourierFTModel,
#     XLoraConfig,
#     XLoraModel,
#     HRAConfig,
#     HRAModel,
#     VBLoRAConfig,
#     get_eva_state_dict,
#     initialize_lora_eva_weights,
#     CPTEmbedding,
#     CPTConfig,
#     BoneConfig,
#     BoneModel,
# )
# from .utils import (
#     TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,
#     PeftType,
#     TaskType,
#     bloom_model_postprocess_past_key_value,
#     get_peft_model_state_dict,
#     prepare_model_for_kbit_training,
#     replace_lora_weights_loftq,
#     set_peft_model_state_dict,
#     shift_tokens_right,
#     load_peft_weights,
#     cast_mixed_precision_params,
# )
from .config import PeftConfig
#, PromptLearningConfig